server.port=${PORT:8082}
spring.application.name=workflow-backend

jwt.secret={JWT_SECRET:mysupersecretkey123456fhgjklmrfgjbhnjkmdfcgvgbnmdcgfhbjnfcvghnvhbn}
jwt.expiration=86400000

app.security.enabled=true

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled=true

spring.datasource.url=jdbc:postgresql://dpg-d6uoq27diees73ckjhsg-a.oregon-postgres.render.com:5432/halleyx_db_81sl
spring.datasource.username=halleyx_db_81sl_user
spring.datasource.password=yAKQVKM5i7ntz0jpo4QfB7eLkqiYhfLT

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration